name: DockerCI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: GitClone
      run: |
        git clone https://github.com/kumarnitesh2000/kubManifest.git
        cd kubManifest/sketch_app/deployment
    - name: PythonScript  
    - run: python lol.py $(git rev-parse --short "$GITHUB_SHA") 
    - name: DockerLogin
      env:
        USER: ${{ secrets.DOCERHUB_USER }}
        PASSWD: ${{ secrets.DOCKERHUB_PASSWD }}
      run: |
        docker login -u $USER -p $PASSWD 
    - name: PrintCommit
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        git_branch=${GITHUB_REF##*/}
        echo $git_branch
        echo $git_hash   
    - name: Build DockerImage
      env: 
        hash: $(git rev-parse --short "$GITHUB_SHA")
      run: |
        docker build -t kumarnitesh2000/sketch_backend:$(git rev-parse --short "$GITHUB_SHA") .
        echo $hash
    - name: Push DockerImage
      env: 
        hash: $(git rev-parse --short "$GITHUB_SHA") 
      run: |
        docker push kumarnitesh2000/sketch_backend:$(git rev-parse --short "$GITHUB_SHA")  
        
